const DOMAINS = [
    {
        id: "web-frontend", name: "Web Development (Frontend)", icon: "🌐", cat: "Tech", color: "#3b82f6", steps: [
            { title: "HTML & CSS Fundamentals", desc: "Build structured web pages with semantic HTML and style them with CSS.", dur: "3-4 weeks", courses: [{ name: "HTML & CSS Full Course", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/responsive-web-design/" }, { name: "Web Design for Beginners", platform: "Udemy", url: "https://www.udemy.com/course/web-design-for-beginners-real-world-coding-in-html-css/" }] },
            { title: "JavaScript Essentials", desc: "Master variables, functions, DOM manipulation, and async programming.", dur: "4-6 weeks", courses: [{ name: "JavaScript Algorithms & DS", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/" }, { name: "The Complete JavaScript Course", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-javascript-course/" }] },
            { title: "Responsive & Modern CSS", desc: "Flexbox, Grid, animations, and mobile-first design patterns.", dur: "2-3 weeks", courses: [{ name: "CSS - The Complete Guide", platform: "Udemy", url: "https://www.udemy.com/course/css-the-complete-guide-incl-flexbox-grid-sass/" }, { name: "Responsive Web Design", platform: "Coursera", url: "https://www.coursera.org/learn/responsivedesign" }] },
            { title: "React or Vue Framework", desc: "Component-based UI development with state management and routing.", dur: "6-8 weeks", courses: [{ name: "React - The Complete Guide", platform: "Udemy", url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/" }, { name: "Vue.js 3 Fundamentals", platform: "Vue Mastery", url: "https://www.vuemastery.com/courses/intro-to-vue-3/intro-to-vue3" }] },
            { title: "Advanced: Testing & Performance", desc: "Unit testing, E2E testing, lazy loading, and performance optimization.", dur: "3-4 weeks", courses: [{ name: "Testing React with Jest", platform: "Udemy", url: "https://www.udemy.com/course/react-testing-with-jest-and-enzyme/" }, { name: "Web Performance", platform: "Google", url: "https://web.dev/learn/#performance" }] }
        ]
    },
    {
        id: "web-backend", name: "Web Development (Backend)", icon: "⚙️", cat: "Tech", color: "#22c55e", steps: [
            { title: "Node.js & Server Basics", desc: "Understand server-side JavaScript, modules, and the event loop.", dur: "3-4 weeks", courses: [{ name: "Node.js Course", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/back-end-development-and-apis/" }, { name: "Node.js - The Complete Guide", platform: "Udemy", url: "https://www.udemy.com/course/nodejs-the-complete-guide/" }] },
            { title: "Express & REST APIs", desc: "Build RESTful APIs with Express, middleware, and routing.", dur: "3-4 weeks", courses: [{ name: "Building RESTful APIs", platform: "Coursera", url: "https://www.coursera.org/learn/building-restful-apis" }, { name: "Express.js Fundamentals", platform: "Udemy", url: "https://www.udemy.com/course/just-express-with-a-bunch-of-node-and-http-in-detail/" }] },
            { title: "Databases (SQL & NoSQL)", desc: "Data modeling, queries with PostgreSQL, MongoDB, and ORMs.", dur: "4-5 weeks", courses: [{ name: "SQL and PostgreSQL", platform: "Udemy", url: "https://www.udemy.com/course/sql-and-postgresql/" }, { name: "MongoDB University", platform: "MongoDB", url: "https://university.mongodb.com/" }] },
            { title: "Authentication & Security", desc: "JWT, OAuth, hashing, HTTPS, and security best practices.", dur: "2-3 weeks", courses: [{ name: "Web Security", platform: "Stanford Online", url: "https://online.stanford.edu/" }, { name: "Node Auth Tutorial", platform: "YouTube", url: "https://www.youtube.com/watch?v=SnoAwLP1a-0" }] },
            { title: "Deployment & DevOps Basics", desc: "Docker, CI/CD, cloud hosting with AWS/Heroku/Vercel.", dur: "3-4 weeks", courses: [{ name: "Docker & Kubernetes", platform: "Udemy", url: "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/" }, { name: "AWS Cloud Practitioner", platform: "AWS", url: "https://aws.amazon.com/training/" }] }
        ]
    },
    {
        id: "data-science", name: "Data Science", icon: "📊", cat: "Tech", color: "#a855f7", steps: [
            { title: "Python Programming", desc: "Core Python, data types, control flow, functions, and OOP.", dur: "4-5 weeks", courses: [{ name: "Python for Everybody", platform: "Coursera", url: "https://www.coursera.org/specializations/python" }, { name: "Automate the Boring Stuff", platform: "Udemy", url: "https://www.udemy.com/course/automate/" }] },
            { title: "Statistics & Probability", desc: "Descriptive stats, probability distributions, hypothesis testing.", dur: "4-5 weeks", courses: [{ name: "Statistics with Python", platform: "Coursera", url: "https://www.coursera.org/specializations/statistics-with-python" }, { name: "Statistics Fundamentals", platform: "Khan Academy", url: "https://www.khanacademy.org/math/statistics-probability" }] },
            { title: "Pandas & Data Wrangling", desc: "Data cleaning, manipulation, and exploratory data analysis.", dur: "3-4 weeks", courses: [{ name: "Data Analysis with Python", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/data-analysis-with-python/" }, { name: "Pandas Complete Tutorial", platform: "Kaggle", url: "https://www.kaggle.com/learn/pandas" }] },
            { title: "Data Visualization", desc: "Matplotlib, Seaborn, Plotly for insightful visual storytelling.", dur: "2-3 weeks", courses: [{ name: "Data Visualization with Python", platform: "Coursera", url: "https://www.coursera.org/learn/python-for-data-visualization" }, { name: "Plotly & Dash", platform: "Udemy", url: "https://www.udemy.com/course/interactive-python-dashboards-with-plotly-and-dash/" }] },
            { title: "Machine Learning Basics", desc: "Regression, classification, clustering with scikit-learn.", dur: "6-8 weeks", courses: [{ name: "Machine Learning", platform: "Coursera", url: "https://www.coursera.org/learn/machine-learning" }, { name: "ML with Python", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/machine-learning-with-python/" }] },
            { title: "Deep Learning & Projects", desc: "Neural networks with TensorFlow/PyTorch and real-world projects.", dur: "6-8 weeks", courses: [{ name: "Deep Learning Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/deep-learning" }, { name: "Practical Deep Learning", platform: "fast.ai", url: "https://course.fast.ai/" }] }
        ]
    },
    {
        id: "ml-ai", name: "Machine Learning & AI", icon: "🤖", cat: "Tech", color: "#ec4899", steps: [
            { title: "Math Foundations", desc: "Linear algebra, calculus, probability — the math behind ML.", dur: "5-6 weeks", courses: [{ name: "Mathematics for ML", platform: "Coursera", url: "https://www.coursera.org/specializations/mathematics-machine-learning" }, { name: "Linear Algebra", platform: "Khan Academy", url: "https://www.khanacademy.org/math/linear-algebra" }] },
            { title: "Python for ML", desc: "NumPy, Pandas, Matplotlib — the Python ML toolkit.", dur: "3-4 weeks", courses: [{ name: "Python for Data Science", platform: "edX", url: "https://www.edx.org/course/python-for-data-science" }, { name: "NumPy & Pandas Crash Course", platform: "Kaggle", url: "https://www.kaggle.com/learn/python" }] },
            { title: "Classical ML Algorithms", desc: "Linear/logistic regression, SVMs, random forests, boosting.", dur: "6-8 weeks", courses: [{ name: "ML by Stanford", platform: "Coursera", url: "https://www.coursera.org/learn/machine-learning" }, { name: "Hands-On ML", platform: "O'Reilly", url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/" }] },
            { title: "Deep Learning", desc: "CNNs, RNNs, transformers with TensorFlow and PyTorch.", dur: "6-8 weeks", courses: [{ name: "Deep Learning Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/deep-learning" }, { name: "PyTorch for Deep Learning", platform: "Udemy", url: "https://www.udemy.com/course/pytorch-for-deep-learning/" }] },
            { title: "NLP & Computer Vision", desc: "Text processing, image recognition, and generative models.", dur: "4-6 weeks", courses: [{ name: "NLP Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/natural-language-processing" }, { name: "CS231n", platform: "Stanford", url: "http://cs231n.stanford.edu/" }] },
            { title: "MLOps & Deployment", desc: "Model serving, monitoring, and production ML pipelines.", dur: "3-4 weeks", courses: [{ name: "MLOps Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops" }, { name: "ML System Design", platform: "Stanford", url: "https://stanford-cs329s.github.io/" }] }
        ]
    },
    {
        id: "cybersecurity", name: "Cybersecurity", icon: "🔒", cat: "Tech", color: "#ef4444", steps: [
            { title: "Networking Fundamentals", desc: "TCP/IP, DNS, HTTP, firewalls, and network architecture.", dur: "4-5 weeks", courses: [{ name: "Computer Networking", platform: "Coursera", url: "https://www.coursera.org/learn/computer-networking" }, { name: "CompTIA Network+", platform: "Udemy", url: "https://www.udemy.com/course/comptia-network-cert-n10-007-the-total-course/" }] },
            { title: "Linux & Command Line", desc: "Linux administration, bash scripting, and system hardening.", dur: "3-4 weeks", courses: [{ name: "Linux Fundamentals", platform: "edX", url: "https://www.edx.org/course/introduction-to-linux" }, { name: "Linux Command Line", platform: "Udemy", url: "https://www.udemy.com/course/linux-mastery/" }] },
            { title: "Security Fundamentals", desc: "CIA triad, encryption, authentication, and risk management.", dur: "4-5 weeks", courses: [{ name: "Cybersecurity Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/cyber-security" }, { name: "CompTIA Security+", platform: "Udemy", url: "https://www.udemy.com/course/comptia-security-certification-sy0-601-the-total-course/" }] },
            { title: "Ethical Hacking", desc: "Penetration testing, vulnerability scanning, and exploitation.", dur: "6-8 weeks", courses: [{ name: "Ethical Hacking", platform: "Udemy", url: "https://www.udemy.com/course/learn-ethical-hacking-from-scratch/" }, { name: "Hack The Box", platform: "HTB", url: "https://www.hackthebox.com/" }] },
            { title: "Advanced & Certifications", desc: "Incident response, forensics, and industry certifications.", dur: "8-12 weeks", courses: [{ name: "CISSP Prep", platform: "Cybrary", url: "https://www.cybrary.it/" }, { name: "TryHackMe", platform: "TryHackMe", url: "https://tryhackme.com/" }] }
        ]
    },
    {
        id: "mobile-dev", name: "Mobile App Development", icon: "📱", cat: "Tech", color: "#f59e0b", steps: [
            { title: "Programming Foundations", desc: "Kotlin for Android or Swift for iOS — pick your platform.", dur: "4-5 weeks", courses: [{ name: "Kotlin for Beginners", platform: "Udemy", url: "https://www.udemy.com/course/kotlin-for-beginners/" }, { name: "Swift Programming", platform: "Apple", url: "https://developer.apple.com/swift/" }] },
            { title: "UI Development", desc: "Jetpack Compose (Android) or SwiftUI (iOS) for modern UIs.", dur: "4-5 weeks", courses: [{ name: "Android Development", platform: "Google", url: "https://developer.android.com/courses" }, { name: "iOS & Swift Bootcamp", platform: "Udemy", url: "https://www.udemy.com/course/ios-13-app-development-bootcamp/" }] },
            { title: "APIs & Data Storage", desc: "REST API integration, local databases, and data persistence.", dur: "3-4 weeks", courses: [{ name: "Networking in Android", platform: "Udemy", url: "https://www.udemy.com/course/android-networking/" }, { name: "Core Data & SwiftUI", platform: "Hacking with Swift", url: "https://www.hackingwithswift.com/" }] },
            { title: "Cross-Platform (Flutter/RN)", desc: "Build for both platforms with React Native or Flutter.", dur: "6-8 weeks", courses: [{ name: "Flutter & Dart", platform: "Udemy", url: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/" }, { name: "React Native", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-react-native-and-redux-course/" }] },
            { title: "Publishing & Monetization", desc: "App Store optimization, analytics, and revenue strategies.", dur: "2-3 weeks", courses: [{ name: "App Marketing", platform: "Udemy", url: "https://www.udemy.com/course/app-marketing/" }, { name: "Play Console Guide", platform: "Google", url: "https://play.google.com/console/about/" }] }
        ]
    },
    {
        id: "cloud", name: "Cloud Computing", icon: "☁️", cat: "Tech", color: "#06b6d4", steps: [
            { title: "Linux & Networking", desc: "Linux admin, networking basics, and virtualization.", dur: "4-5 weeks", courses: [{ name: "Linux Fundamentals", platform: "edX", url: "https://www.edx.org/course/introduction-to-linux" }, { name: "Networking Basics", platform: "Cisco", url: "https://www.netacad.com/" }] },
            { title: "AWS / Azure / GCP Basics", desc: "Core cloud services, IAM, compute, storage, and networking.", dur: "5-6 weeks", courses: [{ name: "AWS Cloud Practitioner", platform: "AWS", url: "https://aws.amazon.com/certification/certified-cloud-practitioner/" }, { name: "Azure Fundamentals", platform: "Microsoft", url: "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/" }] },
            { title: "Containers & Docker", desc: "Containerization, Docker images, compose, and registries.", dur: "3-4 weeks", courses: [{ name: "Docker Mastery", platform: "Udemy", url: "https://www.udemy.com/course/docker-mastery/" }, { name: "Docker Getting Started", platform: "Docker", url: "https://docs.docker.com/get-started/" }] },
            { title: "Kubernetes & Orchestration", desc: "K8s clusters, pods, services, deployments, and Helm.", dur: "4-6 weeks", courses: [{ name: "Kubernetes Course", platform: "Udemy", url: "https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/" }, { name: "K8s Official Tutorials", platform: "Kubernetes", url: "https://kubernetes.io/docs/tutorials/" }] },
            { title: "Infrastructure as Code", desc: "Terraform, CloudFormation, and automated provisioning.", dur: "3-4 weeks", courses: [{ name: "Terraform Course", platform: "Udemy", url: "https://www.udemy.com/course/terraform-beginner-to-advanced/" }, { name: "IaC on AWS", platform: "AWS", url: "https://aws.amazon.com/cloudformation/" }] }
        ]
    },
    {
        id: "devops", name: "DevOps", icon: "🔄", cat: "Tech", color: "#8b5cf6", steps: [
            { title: "Version Control (Git)", desc: "Git workflows, branching, merging, and collaboration on GitHub.", dur: "2-3 weeks", courses: [{ name: "Git & GitHub", platform: "Udemy", url: "https://www.udemy.com/course/git-and-github-bootcamp/" }, { name: "Git Course", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/news/git-and-github-for-beginners/" }] },
            { title: "CI/CD Pipelines", desc: "Jenkins, GitHub Actions, automated testing and deployment.", dur: "3-4 weeks", courses: [{ name: "CI/CD with Jenkins", platform: "Udemy", url: "https://www.udemy.com/course/jenkins-from-zero-to-hero/" }, { name: "GitHub Actions", platform: "GitHub", url: "https://docs.github.com/en/actions" }] },
            { title: "Containers & Docker", desc: "Build, ship, and run applications in containers.", dur: "3-4 weeks", courses: [{ name: "Docker Mastery", platform: "Udemy", url: "https://www.udemy.com/course/docker-mastery/" }, { name: "Docker Docs", platform: "Docker", url: "https://docs.docker.com/" }] },
            { title: "Kubernetes", desc: "Orchestrate containers at scale with Kubernetes.", dur: "4-6 weeks", courses: [{ name: "CKA Course", platform: "Udemy", url: "https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/" }, { name: "K8s Tutorials", platform: "Kubernetes", url: "https://kubernetes.io/docs/tutorials/" }] },
            { title: "Monitoring & Observability", desc: "Prometheus, Grafana, ELK stack, and alerting systems.", dur: "3-4 weeks", courses: [{ name: "Monitoring with Prometheus", platform: "Udemy", url: "https://www.udemy.com/course/monitoring-and-alerting-with-prometheus/" }, { name: "Grafana Tutorials", platform: "Grafana", url: "https://grafana.com/tutorials/" }] }
        ]
    },
    {
        id: "blockchain", name: "Blockchain & Web3", icon: "⛓️", cat: "Tech", color: "#f97316", steps: [
            { title: "Blockchain Fundamentals", desc: "Distributed ledgers, consensus mechanisms, and cryptography.", dur: "3-4 weeks", courses: [{ name: "Blockchain Basics", platform: "Coursera", url: "https://www.coursera.org/learn/blockchain-basics" }, { name: "Blockchain 101", platform: "Udemy", url: "https://www.udemy.com/course/blockchain-and-bitcoin-fundamentals/" }] },
            { title: "Solidity & Smart Contracts", desc: "Write smart contracts for EVM-compatible blockchains.", dur: "5-6 weeks", courses: [{ name: "Solidity by Example", platform: "Solidity", url: "https://solidity-by-example.org/" }, { name: "Ethereum & Solidity", platform: "Udemy", url: "https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/" }] },
            { title: "DApp Development", desc: "Build decentralized applications with Web3.js/Ethers.js.", dur: "4-6 weeks", courses: [{ name: "Full Stack Web3", platform: "freeCodeCamp", url: "https://www.freecodecamp.org/news/learn-blockchain-solidity-full-stack-javascript/" }, { name: "Buildspace", platform: "Buildspace", url: "https://buildspace.so/" }] },
            { title: "DeFi & NFTs", desc: "Decentralized finance protocols and NFT marketplaces.", dur: "3-4 weeks", courses: [{ name: "DeFi Fundamentals", platform: "Finematics", url: "https://finematics.com/" }, { name: "NFT Development", platform: "Udemy", url: "https://www.udemy.com/course/nft-marketplace/" }] },
            { title: "Advanced & Security", desc: "Smart contract auditing, gas optimization, and L2 solutions.", dur: "4-6 weeks", courses: [{ name: "Smart Contract Security", platform: "OpenZeppelin", url: "https://docs.openzeppelin.com/" }, { name: "Ethernaut", platform: "Ethernaut", url: "https://ethernaut.openzeppelin.com/" }] }
        ]
    },
    {
        id: "game-dev", name: "Game Development", icon: "🎮", cat: "Creative", color: "#10b981", steps: [
            { title: "Programming Basics (C#/C++)", desc: "Core programming in C# (Unity) or C++ (Unreal Engine).", dur: "4-6 weeks", courses: [{ name: "C# Fundamentals", platform: "Udemy", url: "https://www.udemy.com/course/csharp-tutorial-for-absolute-beginners/" }, { name: "C++ Programming", platform: "Udemy", url: "https://www.udemy.com/course/beginning-c-plus-plus-programming/" }] },
            { title: "Game Engine (Unity/Unreal)", desc: "Learn your chosen engine's editor, scenes, and workflow.", dur: "5-6 weeks", courses: [{ name: "Unity Complete Course", platform: "Udemy", url: "https://www.udemy.com/course/unitycourse2/" }, { name: "Unreal Engine 5", platform: "Udemy", url: "https://www.udemy.com/course/unrealcourse/" }] },
            { title: "2D Game Development", desc: "Sprites, physics, tilemaps, and 2D game mechanics.", dur: "4-5 weeks", courses: [{ name: "2D Game Dev in Unity", platform: "Udemy", url: "https://www.udemy.com/course/unity-2d-game-development/" }, { name: "2D Platformer Tutorial", platform: "Unity", url: "https://learn.unity.com/" }] },
            { title: "3D Game Development", desc: "3D modeling, lighting, cameras, and 3D game mechanics.", dur: "6-8 weeks", courses: [{ name: "3D Dev in Unity", platform: "Udemy", url: "https://www.udemy.com/course/unitycourse/" }, { name: "3D in Unreal", platform: "Unreal", url: "https://dev.epicgames.com/community/unreal-engine/learning" }] },
            { title: "Publishing & Monetization", desc: "Platform publishing, marketing, and monetization strategies.", dur: "2-3 weeks", courses: [{ name: "Game Marketing", platform: "Udemy", url: "https://www.udemy.com/course/game-marketing/" }, { name: "Steam Direct", platform: "Steam", url: "https://partner.steamgames.com/" }] }
        ]
    },
    {
        id: "uiux", name: "UI/UX Design", icon: "🎨", cat: "Creative", color: "#d946ef", steps: [
            { title: "Design Principles", desc: "Color theory, typography, layout, visual hierarchy, and Gestalt.", dur: "3-4 weeks", courses: [{ name: "Graphic Design Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/graphic-design" }, { name: "Design Fundamentals", platform: "Udemy", url: "https://www.udemy.com/course/graphic-design-fundamentals/" }] },
            { title: "Figma Mastery", desc: "Components, auto-layout, prototyping, and design systems.", dur: "4-5 weeks", courses: [{ name: "Figma UI/UX Design", platform: "Udemy", url: "https://www.udemy.com/course/figma-ux-ui-design-user-experience-tutorial-course/" }, { name: "Figma Tutorials", platform: "Figma", url: "https://www.figma.com/resources/learn-design/" }] },
            { title: "User Research", desc: "User interviews, personas, journey mapping, and usability testing.", dur: "3-4 weeks", courses: [{ name: "UX Research", platform: "Coursera", url: "https://www.coursera.org/learn/ux-research-at-scale" }, { name: "User Research Methods", platform: "NNGroup", url: "https://www.nngroup.com/" }] },
            { title: "Prototyping & Testing", desc: "Interactive prototypes, A/B testing, and iterative design.", dur: "3-4 weeks", courses: [{ name: "Advanced Prototyping", platform: "Udemy", url: "https://www.udemy.com/course/figma-masterclass/" }, { name: "UX Design Process", platform: "Google", url: "https://www.coursera.org/professional-certificates/google-ux-design" }] },
            { title: "Design Systems & Portfolio", desc: "Build a design system, create case studies, and launch your portfolio.", dur: "4-5 weeks", courses: [{ name: "Design Systems", platform: "Figma", url: "https://www.designsystems.com/" }, { name: "Portfolio Building", platform: "Dribbble", url: "https://dribbble.com/stories/categories/tools-tutorials" }] }
        ]
    },
    {
        id: "digital-marketing", name: "Digital Marketing", icon: "📣", cat: "Business", color: "#f43f5e", steps: [
            { title: "SEO Fundamentals", desc: "On-page, off-page, technical SEO, and keyword research.", dur: "3-4 weeks", courses: [{ name: "SEO Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/seo" }, { name: "SEO Training", platform: "Moz", url: "https://moz.com/learn/seo" }] },
            { title: "Social Media Marketing", desc: "Platform strategies, content planning, and audience growth.", dur: "3-4 weeks", courses: [{ name: "Social Media Marketing", platform: "Coursera", url: "https://www.coursera.org/specializations/social-media-marketing" }, { name: "Social Media Course", platform: "HubSpot", url: "https://academy.hubspot.com/" }] },
            { title: "Content Marketing", desc: "Content strategy, copywriting, blogging, and email marketing.", dur: "3-4 weeks", courses: [{ name: "Content Strategy", platform: "Coursera", url: "https://www.coursera.org/learn/content-strategy" }, { name: "Copywriting Course", platform: "Udemy", url: "https://www.udemy.com/course/copywriting-secrets/" }] },
            { title: "Analytics & Data", desc: "Google Analytics, conversion tracking, and data-driven decisions.", dur: "3-4 weeks", courses: [{ name: "Google Analytics Cert", platform: "Google", url: "https://skillshop.withgoogle.com/" }, { name: "Data Analytics", platform: "Coursera", url: "https://www.coursera.org/professional-certificates/google-data-analytics" }] },
            { title: "Paid Ads & PPC", desc: "Google Ads, Facebook Ads, campaign optimization, and ROAS.", dur: "4-5 weeks", courses: [{ name: "Google Ads Certification", platform: "Google", url: "https://skillshop.withgoogle.com/" }, { name: "Facebook Ads Course", platform: "Udemy", url: "https://www.udemy.com/course/facebook-ads-facebook-marketing-mastery-guide/" }] }
        ]
    },
    {
        id: "data-eng", name: "Data Engineering", icon: "🔧", cat: "Tech", color: "#0ea5e9", steps: [
            { title: "SQL Mastery", desc: "Advanced SQL, window functions, query optimization.", dur: "3-4 weeks", courses: [{ name: "SQL for Data Science", platform: "Coursera", url: "https://www.coursera.org/learn/sql-for-data-science" }, { name: "Advanced SQL", platform: "DataCamp", url: "https://www.datacamp.com/" }] },
            { title: "Python for Data Eng", desc: "Python scripting, file handling, and automation.", dur: "3-4 weeks", courses: [{ name: "Python Programming", platform: "Coursera", url: "https://www.coursera.org/specializations/python" }, { name: "Python for Data Eng", platform: "DataCamp", url: "https://www.datacamp.com/" }] },
            { title: "ETL Pipelines", desc: "Extract, transform, load — building data pipelines with Airflow.", dur: "4-5 weeks", courses: [{ name: "Apache Airflow", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow/" }, { name: "Data Engineering", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Data Warehousing", desc: "Snowflake, BigQuery, Redshift, and dimensional modeling.", dur: "4-5 weeks", courses: [{ name: "Data Warehousing", platform: "Coursera", url: "https://www.coursera.org/learn/dwdesign" }, { name: "Snowflake Essentials", platform: "Udemy", url: "https://www.udemy.com/course/snowflake-essentials/" }] },
            { title: "Apache Spark & Streaming", desc: "Big data processing with Spark and real-time streaming.", dur: "4-6 weeks", courses: [{ name: "Apache Spark with Python", platform: "Udemy", url: "https://www.udemy.com/course/spark-and-python-for-big-data-with-pyspark/" }, { name: "Spark Fundamentals", platform: "Databricks", url: "https://www.databricks.com/learn" }] }
        ]
    },
    {
        id: "iot", name: "Embedded Systems & IoT", icon: "🔌", cat: "Engineering", color: "#14b8a6", steps: [
            { title: "Electronics Basics", desc: "Circuits, components, voltage, current, and breadboarding.", dur: "3-4 weeks", courses: [{ name: "Electronics Fundamentals", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Basic Electronics", platform: "Udemy", url: "https://www.udemy.com/course/basic-electronics/" }] },
            { title: "C Programming", desc: "Embedded C, memory management, and low-level programming.", dur: "4-5 weeks", courses: [{ name: "C Programming", platform: "Udemy", url: "https://www.udemy.com/course/c-programming-for-beginners-/" }, { name: "Embedded C", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Microcontrollers", desc: "Arduino, ESP32, and Raspberry Pi with sensor integration.", dur: "4-5 weeks", courses: [{ name: "Arduino Step by Step", platform: "Udemy", url: "https://www.udemy.com/course/arduino-sbs-17gs/" }, { name: "Raspberry Pi", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "IoT Protocols", desc: "MQTT, HTTP, BLE, WiFi, and cloud IoT platforms.", dur: "3-4 weeks", courses: [{ name: "IoT Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/iot" }, { name: "IoT with AWS", platform: "AWS", url: "https://aws.amazon.com/iot/" }] },
            { title: "IoT Projects & Edge AI", desc: "End-to-end IoT solutions with edge computing and TinyML.", dur: "4-6 weeks", courses: [{ name: "TinyML", platform: "edX", url: "https://www.edx.org/professional-certificate/harvardx-tiny-machine-learning" }, { name: "IoT Projects", platform: "Udemy", url: "https://www.udemy.com/course/iot-internet-of-things/" }] }
        ]
    },
    {
        id: "finance", name: "Finance & Fintech", icon: "💰", cat: "Business", color: "#eab308", steps: [
            { title: "Accounting Basics", desc: "Financial statements, bookkeeping, and accounting principles.", dur: "3-4 weeks", courses: [{ name: "Financial Accounting", platform: "Coursera", url: "https://www.coursera.org/learn/wharton-accounting" }, { name: "Accounting Fundamentals", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Financial Markets", desc: "Stocks, bonds, derivatives, and market analysis.", dur: "4-5 weeks", courses: [{ name: "Financial Markets", platform: "Coursera", url: "https://www.coursera.org/learn/financial-markets-global" }, { name: "Investing Course", platform: "Udemy", url: "https://www.udemy.com/course/the-complete-financial-analyst-course/" }] },
            { title: "Financial Modeling", desc: "Excel modeling, DCF analysis, and valuation techniques.", dur: "4-5 weeks", courses: [{ name: "Financial Modeling", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Excel Financial Modeling", platform: "Udemy", url: "https://www.udemy.com/course/financial-modeling-course/" }] },
            { title: "Algorithmic Trading", desc: "Python for quant trading, backtesting, and strategy development.", dur: "5-6 weeks", courses: [{ name: "Algo Trading with Python", platform: "Udemy", url: "https://www.udemy.com/course/algorithmic-trading-with-python/" }, { name: "Quantitative Finance", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Blockchain in Finance", desc: "DeFi, cryptocurrency, and blockchain payment systems.", dur: "3-4 weeks", courses: [{ name: "Blockchain & Crypto", platform: "Coursera", url: "https://www.coursera.org/learn/blockchain-basics" }, { name: "DeFi Course", platform: "Udemy", url: "https://www.udemy.com/course/defi-decentralized-finance/" }] }
        ]
    },
    {
        id: "graphic-design", name: "Graphic Design", icon: "🖌️", cat: "Creative", color: "#e879f9", steps: [
            { title: "Design Theory", desc: "Color, typography, composition, and visual communication.", dur: "3-4 weeks", courses: [{ name: "Graphic Design", platform: "Coursera", url: "https://www.coursera.org/specializations/graphic-design" }, { name: "Design Theory", platform: "Udemy", url: "https://www.udemy.com/course/graphic-design-masterclass/" }] },
            { title: "Adobe Photoshop", desc: "Photo editing, compositing, and digital art with Photoshop.", dur: "4-5 weeks", courses: [{ name: "Photoshop Masterclass", platform: "Udemy", url: "https://www.udemy.com/course/ultimate-photoshop-training-from-beginner-to-pro/" }, { name: "Photoshop Tutorials", platform: "Adobe", url: "https://helpx.adobe.com/photoshop/tutorials.html" }] },
            { title: "Adobe Illustrator", desc: "Vector graphics, logo design, and illustration.", dur: "4-5 weeks", courses: [{ name: "Illustrator CC", platform: "Udemy", url: "https://www.udemy.com/course/adobe-illustrator-cc-tutorial/" }, { name: "Illustrator Tutorials", platform: "Adobe", url: "https://helpx.adobe.com/illustrator/tutorials.html" }] },
            { title: "Branding & Identity", desc: "Logo design, brand guidelines, and visual identity systems.", dur: "3-4 weeks", courses: [{ name: "Brand Identity Design", platform: "Skillshare", url: "https://www.skillshare.com/" }, { name: "Logo Design Mastery", platform: "Udemy", url: "https://www.udemy.com/course/logo-design-mastery-in-adobe-illustrator/" }] },
            { title: "Portfolio & Freelancing", desc: "Build your portfolio, find clients, and manage projects.", dur: "2-3 weeks", courses: [{ name: "Freelance Design", platform: "Skillshare", url: "https://www.skillshare.com/" }, { name: "Portfolio Building", platform: "Behance", url: "https://www.behance.net/" }] }
        ]
    },
    {
        id: "video-editing", name: "Video Editing & Animation", icon: "🎬", cat: "Creative", color: "#fb923c", steps: [
            { title: "Premiere Pro Basics", desc: "Editing workflow, cuts, transitions, and audio syncing.", dur: "3-4 weeks", courses: [{ name: "Premiere Pro Complete", platform: "Udemy", url: "https://www.udemy.com/course/premiere-pro-course/" }, { name: "Premiere Tutorials", platform: "Adobe", url: "https://helpx.adobe.com/premiere-pro/tutorials.html" }] },
            { title: "After Effects", desc: "Motion graphics, visual effects, and compositing.", dur: "4-6 weeks", courses: [{ name: "After Effects CC", platform: "Udemy", url: "https://www.udemy.com/course/after-effects-kinetic-typography/" }, { name: "AE Tutorials", platform: "Adobe", url: "https://helpx.adobe.com/after-effects/tutorials.html" }] },
            { title: "Motion Graphics", desc: "Animate logos, titles, and infographics for professional content.", dur: "4-5 weeks", courses: [{ name: "Motion Design School", platform: "MDS", url: "https://motiondesign.school/" }, { name: "Motion Graphics", platform: "Skillshare", url: "https://www.skillshare.com/" }] },
            { title: "Color Grading & Sound", desc: "DaVinci Resolve color grading and audio mixing.", dur: "3-4 weeks", courses: [{ name: "DaVinci Resolve", platform: "BMD", url: "https://www.blackmagicdesign.com/products/davinciresolve/training" }, { name: "Color Grading", platform: "Udemy", url: "https://www.udemy.com/course/color-grading/" }] },
            { title: "3D Animation Intro", desc: "Blender basics, 3D modeling, and animation fundamentals.", dur: "5-6 weeks", courses: [{ name: "Blender Complete", platform: "Udemy", url: "https://www.udemy.com/course/blendertutorial/" }, { name: "Blender Guru", platform: "YouTube", url: "https://www.youtube.com/user/AndrewPPrice" }] }
        ]
    },
    {
        id: "mech-eng", name: "Mechanical Engineering", icon: "⚙️", cat: "Engineering", color: "#64748b", steps: [
            { title: "Physics & Math", desc: "Mechanics, thermodynamics, calculus, and differential equations.", dur: "6-8 weeks", courses: [{ name: "Engineering Mechanics", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Physics", platform: "Khan Academy", url: "https://www.khanacademy.org/science/physics" }] },
            { title: "CAD & 3D Modeling", desc: "SolidWorks, AutoCAD, and Fusion 360 for design.", dur: "5-6 weeks", courses: [{ name: "SolidWorks", platform: "Udemy", url: "https://www.udemy.com/course/solidworks/" }, { name: "Fusion 360", platform: "Autodesk", url: "https://www.autodesk.com/products/fusion-360/learn-training-tutorials" }] },
            { title: "Thermodynamics & Fluids", desc: "Heat transfer, fluid dynamics, and energy systems.", dur: "5-6 weeks", courses: [{ name: "Thermodynamics", platform: "MIT OCW", url: "https://ocw.mit.edu/" }, { name: "Fluid Mechanics", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Manufacturing & Materials", desc: "Manufacturing processes, material science, and quality control.", dur: "4-5 weeks", courses: [{ name: "Manufacturing Processes", platform: "MIT OCW", url: "https://ocw.mit.edu/" }, { name: "Materials Science", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "FEA & Simulation", desc: "Finite element analysis and simulation with ANSYS.", dur: "4-6 weeks", courses: [{ name: "ANSYS Training", platform: "Udemy", url: "https://www.udemy.com/course/ansys/" }, { name: "FEA Fundamentals", platform: "Coursera", url: "https://www.coursera.org/" }] }
        ]
    },
    {
        id: "civil-eng", name: "Civil Engineering", icon: "🏗️", cat: "Engineering", color: "#78716c", steps: [
            { title: "Structural Analysis", desc: "Forces, moments, beams, trusses, and structural systems.", dur: "5-6 weeks", courses: [{ name: "Structural Engineering", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Structural Analysis", platform: "MIT OCW", url: "https://ocw.mit.edu/" }] },
            { title: "AutoCAD & BIM", desc: "2D drafting, 3D modeling, and Building Information Modeling.", dur: "4-5 weeks", courses: [{ name: "AutoCAD Complete", platform: "Udemy", url: "https://www.udemy.com/course/autocad-2d-and-3d-practice-drawings/" }, { name: "Revit BIM", platform: "Udemy", url: "https://www.udemy.com/course/autodesk-revit-architecture/" }] },
            { title: "Surveying & Geotechnics", desc: "Land surveying, soil mechanics, and geotechnical engineering.", dur: "4-5 weeks", courses: [{ name: "Geotechnical Engineering", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Surveying", platform: "NPTEL", url: "https://nptel.ac.in/" }] },
            { title: "Concrete & Steel Design", desc: "Reinforced concrete and steel structure design codes.", dur: "5-6 weeks", courses: [{ name: "Concrete Design", platform: "NPTEL", url: "https://nptel.ac.in/" }, { name: "Steel Design", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Project Management", desc: "Construction management, scheduling, and cost estimation.", dur: "3-4 weeks", courses: [{ name: "Construction Management", platform: "Coursera", url: "https://www.coursera.org/specializations/construction-management" }, { name: "PMP Prep", platform: "Udemy", url: "https://www.udemy.com/course/pmp-certification-exam-prep-course-pmbok-6th-edition/" }] }
        ]
    },
    {
        id: "electrical-eng", name: "Electrical Engineering", icon: "⚡", cat: "Engineering", color: "#facc15", steps: [
            { title: "Circuit Analysis", desc: "Ohm's law, Kirchhoff's laws, AC/DC circuits, and network theorems.", dur: "4-5 weeks", courses: [{ name: "Circuits & Electronics", platform: "edX", url: "https://www.edx.org/" }, { name: "Circuit Analysis", platform: "Khan Academy", url: "https://www.khanacademy.org/science/electrical-engineering" }] },
            { title: "Electronics", desc: "Diodes, transistors, op-amps, and digital logic.", dur: "4-5 weeks", courses: [{ name: "Electronics", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Digital Electronics", platform: "NPTEL", url: "https://nptel.ac.in/" }] },
            { title: "Power Systems", desc: "Generation, transmission, distribution, and renewable energy.", dur: "4-5 weeks", courses: [{ name: "Power Systems", platform: "NPTEL", url: "https://nptel.ac.in/" }, { name: "Renewable Energy", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Control Systems", desc: "Transfer functions, stability analysis, PID controllers.", dur: "4-5 weeks", courses: [{ name: "Control Systems", platform: "MIT OCW", url: "https://ocw.mit.edu/" }, { name: "Control Engineering", platform: "NPTEL", url: "https://nptel.ac.in/" }] },
            { title: "Signal Processing", desc: "Fourier transforms, filtering, and digital signal processing.", dur: "4-6 weeks", courses: [{ name: "DSP", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Signals & Systems", platform: "MIT OCW", url: "https://ocw.mit.edu/" }] }
        ]
    },
    {
        id: "medical", name: "Medical & Healthcare", icon: "🏥", cat: "Science", color: "#f87171", steps: [
            { title: "Anatomy & Physiology", desc: "Human body systems, organs, and functional anatomy.", dur: "8-10 weeks", courses: [{ name: "Anatomy Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/anatomy" }, { name: "Anatomy & Physiology", platform: "Khan Academy", url: "https://www.khanacademy.org/science/biology" }] },
            { title: "Biochemistry & Pathology", desc: "Cellular processes, disease mechanisms, and lab diagnosis.", dur: "6-8 weeks", courses: [{ name: "Biochemistry", platform: "MIT OCW", url: "https://ocw.mit.edu/" }, { name: "Pathology", platform: "Coursera", url: "https://www.coursera.org/" }] },
            { title: "Clinical Skills", desc: "Patient assessment, diagnostic reasoning, and medical procedures.", dur: "8-12 weeks", courses: [{ name: "Clinical Skills", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Medical Education", platform: "Osmosis", url: "https://www.osmosis.org/" }] },
            { title: "Public Health", desc: "Epidemiology, healthcare systems, and population health.", dur: "4-6 weeks", courses: [{ name: "Public Health", platform: "Coursera", url: "https://www.coursera.org/specializations/public-health" }, { name: "Epidemiology", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Specialization Prep", desc: "Choose your specialization and prepare for board exams.", dur: "12+ weeks", courses: [{ name: "Board Review", platform: "AMBOSS", url: "https://www.amboss.com/" }, { name: "USMLE Prep", platform: "UWorld", url: "https://www.uworld.com/" }] }
        ]
    },
    {
        id: "psychology", name: "Psychology", icon: "🧠", cat: "Science", color: "#c084fc", steps: [
            { title: "Intro to Psychology", desc: "History, biological bases, perception, learning, and memory.", dur: "4-5 weeks", courses: [{ name: "Intro to Psychology", platform: "Coursera", url: "https://www.coursera.org/learn/introduction-psychology" }, { name: "Psychology", platform: "Khan Academy", url: "https://www.khanacademy.org/science/ap-psychology" }] },
            { title: "Research Methods", desc: "Experimental design, statistics, and data analysis in psychology.", dur: "4-5 weeks", courses: [{ name: "Research Methods", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Stats for Psychology", platform: "Khan Academy", url: "https://www.khanacademy.org/math/statistics-probability" }] },
            { title: "Developmental & Social", desc: "Lifespan development, social influence, and group behavior.", dur: "4-5 weeks", courses: [{ name: "Social Psychology", platform: "Coursera", url: "https://www.coursera.org/learn/social-psychology" }, { name: "Developmental Psychology", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Clinical Psychology", desc: "Psychological disorders, DSM-5, assessment, and therapy.", dur: "5-6 weeks", courses: [{ name: "Abnormal Psychology", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Clinical Psychology", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Counseling & Therapy", desc: "CBT, motivational interviewing, and therapeutic techniques.", dur: "6-8 weeks", courses: [{ name: "CBT Fundamentals", platform: "Udemy", url: "https://www.udemy.com/course/cognitive-behavioral-therapy/" }, { name: "Counseling Skills", platform: "Coursera", url: "https://www.coursera.org/" }] }
        ]
    },
    {
        id: "business", name: "Business & MBA", icon: "💼", cat: "Business", color: "#0d9488", steps: [
            { title: "Management Fundamentals", desc: "Leadership, organizational behavior, and decision-making.", dur: "4-5 weeks", courses: [{ name: "Management Fundamentals", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Leadership & Management", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Marketing Strategy", desc: "Market analysis, positioning, branding, and go-to-market.", dur: "4-5 weeks", courses: [{ name: "Marketing Strategy", platform: "Coursera", url: "https://www.coursera.org/learn/marketing-strategy" }, { name: "Digital Marketing", platform: "Google", url: "https://skillshop.withgoogle.com/" }] },
            { title: "Corporate Finance", desc: "Capital budgeting, valuation, M&A, and financial planning.", dur: "4-5 weeks", courses: [{ name: "Corporate Finance", platform: "Coursera", url: "https://www.coursera.org/learn/wharton-finance" }, { name: "Finance Essentials", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Operations & Analytics", desc: "Supply chain, process optimization, and business analytics.", dur: "4-5 weeks", courses: [{ name: "Operations Management", platform: "Coursera", url: "https://www.coursera.org/" }, { name: "Business Analytics", platform: "edX", url: "https://www.edx.org/" }] },
            { title: "Strategy & Entrepreneurship", desc: "Competitive strategy, business models, and startup execution.", dur: "4-5 weeks", courses: [{ name: "Business Strategy", platform: "Coursera", url: "https://www.coursera.org/specializations/business-strategy" }, { name: "Entrepreneurship", platform: "edX", url: "https://www.edx.org/" }] }
        ]
    },
    {
        id: "competitive-programming", name: "Competitive Programming", icon: "🏆", cat: "Tech", color: "#6366f1", steps: [
            { title: "C++ Fundamentals", desc: "STL, I/O optimization, and competitive coding setup.", dur: "3-4 weeks", courses: [{ name: "C++ for Competitive", platform: "Udemy", url: "https://www.udemy.com/course/cpp-for-competitive-programming/" }, { name: "C++ STL", platform: "GeeksforGeeks", url: "https://www.geeksforgeeks.org/the-c-standard-template-library-stl/" }] },
            { title: "Data Structures", desc: "Arrays, linked lists, trees, graphs, heaps, and hash maps.", dur: "5-6 weeks", courses: [{ name: "Data Structures", platform: "Coursera", url: "https://www.coursera.org/specializations/data-structures-algorithms" }, { name: "DSA Course", platform: "Udemy", url: "https://www.udemy.com/course/datastructurescncpp/" }] },
            { title: "Algorithms", desc: "Sorting, searching, DP, greedy, divide and conquer.", dur: "5-6 weeks", courses: [{ name: "Algorithms Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/algorithms" }, { name: "Algorithms Course", platform: "MIT OCW", url: "https://ocw.mit.edu/" }] },
            { title: "Advanced Topics", desc: "Segment trees, BIT, string algorithms, and number theory.", dur: "4-6 weeks", courses: [{ name: "Advanced Algorithms", platform: "Codeforces", url: "https://codeforces.com/" }, { name: "CP Handbook", platform: "CSES", url: "https://cses.fi/book/book.pdf" }] },
            { title: "Contest Practice", desc: "Regular practice on Codeforces, LeetCode, and AtCoder.", dur: "Ongoing", courses: [{ name: "LeetCode", platform: "LeetCode", url: "https://leetcode.com/" }, { name: "Codeforces", platform: "Codeforces", url: "https://codeforces.com/" }] }
        ]
    },
    {
        id: "ai-research", name: "AI Research", icon: "🔬", cat: "Science", color: "#818cf8", steps: [
            { title: "Linear Algebra & Calculus", desc: "Matrices, eigenvalues, multivariable calculus, and optimization.", dur: "5-6 weeks", courses: [{ name: "Mathematics for ML", platform: "Coursera", url: "https://www.coursera.org/specializations/mathematics-machine-learning" }, { name: "Linear Algebra", platform: "MIT OCW", url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/" }] },
            { title: "Probability & Statistics", desc: "Bayesian inference, distributions, and statistical learning.", dur: "4-5 weeks", courses: [{ name: "Probability", platform: "MIT OCW", url: "https://ocw.mit.edu/" }, { name: "Statistical Learning", platform: "Stanford Online", url: "https://online.stanford.edu/courses/sohs-ystatslearning-statistical-learning" }] },
            { title: "Machine Learning Theory", desc: "PAC learning, VC dimension, kernel methods, and regularization.", dur: "6-8 weeks", courses: [{ name: "ML Course", platform: "Coursera", url: "https://www.coursera.org/learn/machine-learning" }, { name: "Learning from Data", platform: "Caltech", url: "https://work.caltech.edu/telecourse" }] },
            { title: "Reinforcement Learning", desc: "MDPs, Q-learning, policy gradients, and multi-agent RL.", dur: "5-6 weeks", courses: [{ name: "RL Specialization", platform: "Coursera", url: "https://www.coursera.org/specializations/reinforcement-learning" }, { name: "RL by David Silver", platform: "DeepMind", url: "https://www.davidsilver.uk/teaching/" }] },
            { title: "Reading & Publishing Papers", desc: "Read top-tier papers, reproduce results, and write your own.", dur: "Ongoing", courses: [{ name: "Papers With Code", platform: "PWC", url: "https://paperswithcode.com/" }, { name: "ArXiv", platform: "ArXiv", url: "https://arxiv.org/list/cs.AI/recent" }] }
        ]
    }
];

const CATEGORIES = [
    { id: "all", label: "All Domains", icon: "🌟" },
    { id: "Tech", label: "Technology", icon: "💻" },
    { id: "Creative", label: "Creative Arts", icon: "🎨" },
    { id: "Business", label: "Business", icon: "💼" },
    { id: "Engineering", label: "Engineering", icon: "🔧" },
    { id: "Science", label: "Science", icon: "🔬" }
];
